### ISSUE TITLE
no redirect, but username and password are good

### ISSUE THREAD

**Issue by 0uro** [osresearch/hcpy#14]
Hi, I'm using latest git version

I followed instructions but it keeps failing. I never managed to make it work does anybody else experienced the same ?

Tried setting up https://github.com/alexkn/node-red-contrib-homeconnect with little success (have to redo steps to make it work)

hcpy looks like a better approach... anyway

Do I have to adapt some settings like app_id or scope ?

**Comment by osresearch** [comment]
They changed the login flow to as part of the SingleKey switch and it broke `hc-login`, which was also noted in #13 .  I need to reverse engineer it before my talk about hcpy at the hackaday meetup later this month...

**Comment by osresearch** [comment]
(oops, that was supposed to be closed as "dupe", it is planned!)
