### ISSUE TITLE
Error 404  in log for Dishwasher, resource': '/iz/info'

### ISSUE THREAD

**Issue by KHome** [osresearch/hcpy#18]
In the logs I found this info: 
{'error': 404, 'resource': '/iz/info'}

I don't really know, why and if this is important.
Please have a look and maybe support some further information what "iz" is.

**Comment by osresearch** [comment]
What model do you have? My SX65EX56CN/11 dishwasher reports:

```
2022-01-30 22:47:48.561156 RX: {
'sID': 3060800731,
 'msgID': 1149472062,
 'resource': '/iz/info',
 'version': 1,
 'action': 'RESPONSE',
 'data': [{
   'deviceID': 'XXXX',
   'eNumber': 'SX65EX56CN/11',
   'brand': 'SIEMENS',
   'vib': 'SX65EX56CN',
   'mac': 'XX-XX-XX-XX-XX',
   'haVersion': '1.4',
   'swVersion': '3.2.10.20200911163726',
   'hwVersion': '2.0.0.2',
   'deviceType': 'Dishwasher',
   'deviceInfo': '',
   'customerIndex': '11',
   'serialNumber': 'XXXXX',
   'fdString': '0201',
   'shipSki': 'ABCDEF'
}]}
```

We could add per-device lists of initial URLs to fetch, although it's  harmless to fetch it from the devices that don't support it.

**Comment by KHome** [comment]
{'sID': 643305113, 
'msgID': 2132185890, 
'resource': '/ci/info', 
'version': 2, 
'action': 'RESPONSE', 
'data': [
{'deviceID': 'SIEMENS-SX658X06TE-xxxxxxxx',
 'eNumber': 'SX658X06TE/52', 
'brand': 'SIEMENS', 
'vib': 'SX658X06TE', 
'mac': 'xx-xx-xx-xx-xx-xx', 
'haVersion': '5.0', 
'swVersion': '2.15.1.13325', 
'hwVersion': '1.0.2.2', 
'deviceType': 'Dishwasher', 
'deviceInfo': 'DISHWASHER', 
'customerIndex': '52', 
'serialNumber': 'xxxxxxxxxxxxx', 
'fdString': '99xx', 
'shipSki': 'xxxxxxxx', 
'wifiInterfaces': 1}
]}
