### ISSUE TITLE
hc-login doesn't work with accounts migrated to singlekey

### ISSUE THREAD

**Issue by bdavj** [osresearch/hcpy#20]
After (accidentally?) migrating to SingleKey, hc-login no longer works. 

Response:

<input type="hidden" name="environment" value="PRD"/>

            <div class="panel">
              <div class="panel-body">

                <div class="info_topic_hdr" lng-key="migration.success_hdr">Success!</div>

          <div class="info-txt">
            <span id="migrationFormInfo" lng-key="migration.msg.success">
            Your Home Connect account is connected to SingleKey ID.<br/>
            From now on, you will log in to Home Connect with your SingleKey ID.<br/>
            Enjoy!
            </span>

          </div>

              </div>

              <div class="button-line">

                <button class="submit-btn" type="submit" lng-key="migration.btn.ok">OK</button>

              </div>
            </div>
          </form>

**Comment by osresearch** [comment]
Oh, sorry about that! I didn't realize that would be a consequence of running the updated script.  Since people can't create non-Singlekey logins, I didn't have a way to test with a non-migrated account.

**Comment by bdavj** [comment]
Ahh yes I had been clicking "No thanks" every time in the app (for no particular reason!)

If its of interest, the difference (when it does the migration) is that this request:

`https://api.home-connect.com/security/oauth/redirect_target?code={CODE}-1&scope=openid%20email%20profile%20offline_access%20homeconnect.general&state=%7B%22session_id%{SESSION_ID}&session_state={SESSION_STATE}&iss=https%3A%2F%2Fsinglekey-id.com%2Fauth`

Returns a _200_ with an HTML page saying the above (_From now on you'll log in..._) as opposed to the 302 redirect to the _hcauth://_ url with the _authorization_code_
