### ISSUE TITLE
auth failed with  <Response [400]> 

### ISSUE THREAD

**Issue by phoenix-blue** [osresearch/hcpy#28]
Hello,

I'm trying to run the hc-login with the right username and password, but i'm getting an reponse 400 with an auth. failed error.
I'm sure that the user and password is ok, (double checkt it and can use the same user and password on this site https://singlekey-id.com/nl), but still getting this error.

Any idea how to fixed this?

**Comment by osresearch** [comment]
I just tried to be sure that it still worked for me and things seem ok.  Although we don't have any insight into what happens on their backend or if there are different account states.  Have you logged in to the account with their app to do the device setup already?

Another long shot -- Is there a chance your password has a shell meta character in it that isn't quoted correctly? For instance my password manager created one with a `$` which requires that I put it in single quotes on the command line.

**Comment by osresearch** [comment]
Something broke for me between September and now as well, but luckily @meidlinga fixed it.

**Comment by ericblade** [comment]
fwiw, i'm just trying this out now, and i'm failing as described in #33 .  401 with a malformed token issue.  Password seems to be working, if I completely whiff the password, I get a ```raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '/auth/en-gb/login?returnUrl=%2Fauth%2Fconnect%2Fauthorize%2Fcallback%3...``` error
