### ISSUE TITLE
hc-login: KeyError: 'returnUrl'

### ISSUE THREAD

**Issue by liouma** [osresearch/hcpy#42]
Hello,
I have the following error when running hc-login:

`next preauth_url='https://singlekey-id.com/auth/en-gb/login?ReturnUrl=%2Fauth%2Fconnect%2Fauthorize%2Fcallback%3Fclient_id%3D11F75C04-21C2-4DA9-A623-228B54E9A256%26redirect_uri%3Dhttps%253A%252F%252Fapi.home-connect.com%252Fsecurity%252Foauth%252Fredirect_target%26response_type%3Dcode%26scope%3Dopenid%2520email%2520profile%2520offline_access%2520homeconnect.general%26prompt%3Dlogin%26style_id%3Dbsh_hc_01%26state%3D%257B%2522session_id%2522%253A%25224cf70097-4a00-43fc-8192-3d423766035b%2522%257D%26suppressed_prompt%3Dlogin&f=XPA0'`

`Traceback (most recent call last):`

`  File "/home/domotic/hcpy/./hc-login", line 139, in <module>`

`    return_url = query["returnUrl"][0]`
`                 ~~~~~^^^^^^^^^^^^^`
`KeyError: 'returnUrl'`

All the steps before ran whithout any error.
Any help would be more than welcome!!!

**Comment by andi-at-1** [comment]
i get the same error :-(

**Comment by andi-at-1** [comment]
look at the next error. You have to change hcpy/hcpy/hc-login:
Line 139 needs a capital letter in ReturnUrl, change it to:

return_url = query["ReturnUrl"][0]

**Comment by liouma** [comment]
Nice, well done! !!!!

**Comment by liouma** [comment]
A
